### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by ghost** [nana-4/Adwaita-Alt#2]
Hello, happy new year!

Thank your for your work on Materia. However I remember using this theme when it was released, are you still working on it? I quite like Adwaita but your version is really nice, flatter without being totally flat is something that we don't see anymore.

**Comment by nana-4** [comment]
Happy new year!

I didn't intend to discontinue it, but updating this has been neglected because I don't have much time...
However, this is originally an experimental theme and it is not expected much to use on a daily basis, so updating may be rare anyway. 😉

**Comment by ghost** [comment]
Thank you for your answer :) Yeah I know it's an experimental project but was wondering if you were still working on it or not because I really like it and could use it as my main theme often.

Have a nice day.

**Comment by nana-4** [comment]
Oh, so I will try to update a bit more.

Thanks. You too. :)
